### PR TITLE
Add arg specs

### PR DESCRIPTION
**Pull request by Tompage1994**
# What does this PR do?
Add arg spec for all roles

# How should this be tested?
CI

# Is there a relevant Issue open for this?

N/A

# Other Relevant info, PRs, etc
related https://github.com/redhat-cop/controller_configuration/discussions/509

### CODE REVIEW

**Review by djdanielsson — CHANGES_REQUESTED** [review]
tests are failing

**Comment by Tompage1994** [comment]
> tests are failing

I'll probably have to work through any issues so don't merge whilst this is failing, but once it's passed then we should be good to go. I suspect there will be a few bits where the argspec causes issues here so I'll need to resolve

**Comment by Tompage1994** [comment]
Realising now that changes to CI don't get reflected in PRs anymore because of the workflow. I've fixed the first issue but possibly worth approving this and I'll fix anything broken tomorrow

**Comment by Tompage1994** [comment]
The CI will never work because it's currently broken in main and the new way of running CI means changes to .github aren't used (i.e. it takes the pipeline code from main to run CI)

**Comment by Tompage1994** [comment]
Have raised #246 to fix CI not running against updated test cases

**Pull request merged**
