### PR TITLE
Fix module_utils code

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

* Corrected spelling fixes
* Added missing method
* Simplify the code

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @djdanielsson

**Comment by djdanielsson** [comment]
You tested the changes?

**Comment by Akasurde** [comment]
> You tested the changes?

yes. Most of the code changes are pedantic.

**Review by djdanielsson — APPROVED** [review]
LGTM

**Pull request merged**
