### PR TITLE
Implement basic auth flow to enable keycloak users

### LINKED ISSUE #94: This collection doesn't work with Keycloak users
If using RHSSO to authenticate for AH, this collection does not seem to work (would be good to get someone to verify its not just something wrong with my setup).

I suppose this probably makes sense as it required you to go off to an external site. Its also not possible to log into a user from SSO in the API browser so that probably backs this up. 

We will definitely need to come up with a workaround for this, or at very least give explanation that only local users are supported.

EXTRA: the modules which allow `ah_token` do work with keycloak users only if you pass in `ah_token`

### PR DESCRIPTION
**Pull request by Tompage1994**
### What does this PR do?
Implements basic auth if regular auth doesn't work. Therefore allowing keycloak users to log in

### How should this be tested?
Run against any number of modules should work with both keycloak and local users

### Is there a relevant Issue open for this?
resolves #94

### CODE REVIEW

**Review by djdanielsson — APPROVED** [review]
this will be useful in the coming future for sure. LGTM

**Review by djdanielsson — CHANGES_REQUESTED** [review]
actually i just noticed it looks like one of the linters is failing, can you double check on that.

**Comment by Tompage1994** [comment]
I've updated the code with lint fixes and a slight bugfix.

To test the code I've used the following short playbook where `admin` is a local user, `ansible` is a Keycloak user and then theres an example of an invalid cred to ensure everything fails correctly.

```
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Configure community repo
      redhat_cop.ah_configuration.ah_repository:
        name: community
        url: https://galaxy.ansible.com/api/
        requirements_file: requirements.yml
        ah_host: https://ah.local
        ah_username: admin
        ah_password: password
        validate_certs: false
    - name: Configure community repo
      redhat_cop.ah_configuration.ah_repository:
        name: community
        url: https://galaxy.ansible.com/api/
        requirements_file: requirements.yml
        ah_host: https://ah.local
        ah_username: ansible
        ah_password: password
        validate_certs: false
    - name: Configure community repo
      redhat_cop.ah_configuration.ah_repository:
        name: community
        url: https://galaxy.ansible.com/api/
        requirements_file: requirements.yml
        ah_host: https://ah.local
        ah_username: ansible
        ah_password: passworda
        validate_certs: false
      ignore_errors: true
      register: mod_fail
    - assert:
        that:
          - mod_fail is failed

    - name: Add a remote registry to AH
      redhat_cop.ah_configuration.ah_ee_registry:
        name: my_quayio
        state: present
        url: https://quay.io/my/registry
        ah_hostname: https://ah.local
        ah_username: ansible
        ah_password: password
        validate_certs: false
    - name: Add a remote registry to AH
      redhat_cop.ah_configuration.ah_ee_registry:
        name: my_quayio
        state: present
        url: https://quay.io/my/registry
        ah_hostname: https://ah.local
        ah_username: admin
        ah_password: password
        validate_certs: false
    - name: Add a remote registry to AH
      redhat_cop.ah_configuration.ah_ee_registry:
        name: my_quayio
        state: present
        url: https://quay.io/my/registry
        ah_hostname: https://ah.local
        ah_username: ansible
        ah_password: passworda
        validate_certs: false
      ignore_errors: true
      register: apimod_fail
    - assert:
        that:
          - apimod_fail is failed
```

**Comment by Tompage1994** [comment]
As its a major change I'd like @sean-m-sullivan to also review before merging

**Review by djdanielsson — APPROVED** [review]
LGTM

**Comment by sean-m-sullivan** [comment]
Tested it, and it works, As much as I am hesitant to do non basic auth, I don't see a better choice atm.

**Review by sean-m-sullivan — APPROVED** [review]
LGTM

**Pull request merged**
