### PR TITLE
feat: add filetree_read role for automation hub

### PR DESCRIPTION
**Pull request by jon4hz**
# What does this PR do?
This PR adds a filetree_read role similar to https://github.com/redhat-cop/controller_configuration/tree/devel/roles/filetree_read

# TODO
- [ ] Test playbook
- [ ] README, meta, etc.

### CODE REVIEW

**Comment by djdanielsson** [comment]
I am not sure this is the best place to put this role, due to this will become a supported collection and the filetree roles are a very opinionated way of doing things.

**Comment by sean-m-sullivan** [comment]
agreed this was a sticking point when we were discussing the controller_configuration collections as well, perhaps we create a redhat_cop.filetree collection repository for housing it? I think the primary issue is support and maintenance, I know sometimes I have not been able to figure out how to fix or diagnose issues with the controller set.

**Comment by jon4hz** [comment]
Well, it's up to you where you want to house this :)
I simply found the controller_configuration.filetree_read role quite useful for configuring multiple AAP environments and figured I wanted to configure the automation hub in a same manner.
Please let me know if I should open a PR against another repo.

**Comment by djdanielsson** [comment]
@jon4hz if this is something you are interested in still, see https://github.com/redhat-cop/aap_configuration_extended the new home for roles like this where we can work on developing features like this without affecting the base repo.

**Pull request closed without merging**
