### PR TITLE
Fix of Ci

### LINKED ISSUE #336: Migrate to oci-env for CI workflows
Currently this repo uses the legacy galaxy dev environment that will be soon removed (already unmaintained)

https://github.com/ansible/galaxy_collection/blob/devel/.github/workflows/ci_standalone_versioned.yml#L26 

## Proposal

Move to oci-env to spinup the galaxy server

Reference: https://github.com/ansible/galaxy_ng/blob/eb6bc8197c182f742233a743e3dd9fa962996413/.github/workflows/ci_oci-env-integration.yml#L35-L56

### LINKED ISSUE #374: CI Failing
# Summary
CI is currently failing on all but stable-4.4 

There are different issues for each version but here is my synopsis:

- 4.7 and master are both because they can't reach the URL.
- 4.6 can't build the stack
- 4.5 hangs when uploading the collection

# Issue Type

- Bug Report

# OS / ENVIRONMENT
CI

# Job output
Different outputs shown for each version but the job is here:
https://github.com/ansible/galaxy_collection/actions/runs/8419702286

### PR DESCRIPTION
**Pull request by Tompage1994**
# What does this PR do?
I *think* this should fix all of the CI

It will remove support for everything that currently existed and change the targets to `stable-2.8` and `stable-2.9` and `master`.

# How should this be tested?
Has mostly worked on my fork up until the point of needing registry creds, but nonetheless AH is running and tests are passing https://github.com/Tompage1994/ah_configuration/actions/runs/8424178683/job/23067509134

Won't be working here until merged

# Is there a relevant Issue open for this?

resolves #374 
resolves #336

### CODE REVIEW

**Comment by Tompage1994** [comment]
There is a little bit of stuff needed to be sorted with this, but it's almost there

**Review by sean-m-sullivan — APPROVED** [review]
Lets do it

**Comment by Tompage1994** [comment]
So, CI still broken but at least the stack stands up. Perhaps we merge this and then anyone can work on getting the actual playbooks to work?

**Comment by sean-m-sullivan** [comment]
agreed

**Pull request merged**
