### PR TITLE
Add role option for proxy information

### LINKED ISSUE #263: ah_repository's proxy_* parameters not taken into account
I'm using 1.1.1

Maybe I'm missing something obvious as this is super odd, but I can't get it working.

Take for instance:
```
---
ah_repositories: []
ah_repository_certified:
  url: "https://console.redhat.com/api/automation-hub/content/xxxxx-synclist/"
  auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  proxy_url: "http://myproxy:3131"
  proxy_username: test
  proxy_password: test
  username: usern
  tls_validation: True
  token: !vault | ****
```

All param are processed except `proxy_*`

See the debug log form the ansible-playbook command:
```
changed: [localhost] => {
    "changed": true,
    "id": false,
    "invocation": {
        "module_args": {
            "ah_host": "automationhub.mydomain.com",
            "ah_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ah_path_prefix": "galaxy",
            "ah_token": null,
            "ah_username": "admin",
            "auth_url": "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token",
            "ca_cert": null,
            "ca_cert_path": null,
            "client_cert": null,
            "client_cert_path": null,
            "client_key": null,
            "client_key_path": null,
            "download_concurrency": "10",
            "name": "rh-certified",
            "password": null,
            "proxy_password": null,
            "proxy_url": null,
            "proxy_username": null,
            "rate_limit": "8",
            "requirements": null,
            "requirements_file": null,
            "signed_only": false,
            "tls_validation": true,
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url": "https://console.redhat.com/api/automation-hub/content/xxxxxxxx-synclist/",
            "username": "usern",
            "validate_certs": null
        }
```

I tried to take a peek at the python source code at https://github.com/ansible/ah_configuration/blob/1.1.1/plugins/modules/ah_repository.py#L206

I don't see why proxy_* would be treated differently than for instance "username" which I added as a test.

Hope you can reproduce easily or tell me about something obvious I'm missing

### PR DESCRIPTION
**Pull request by Tompage1994**
# What does this PR do?
Add role option for proxy information rather than being forced to use global

# How should this be tested?
No longer need to set proxy globally

# Is there a relevant Issue open for this?

resolves #263 

# Other Relevant info, PRs, etc
n/a

### CODE REVIEW

**Review by sean-m-sullivan — CHANGES_REQUESTED** [review]
Needs an update in the role readme as well, otherwise LGTM

**Comment by Tompage1994** [comment]
> Needs an update in the role readme as well, otherwise LGTM

Makes sense, I will do that (although it's actually more matching the readme now than it did before 😬)

**Review by sean-m-sullivan — APPROVED** [review]
LGTM

**Review by djdanielsson — COMMENTED** [review]
flake8 is failing, not sure if it is connected to these changes though... wouldn't see why. also the extra spaces I thought was causing some errors which is why I believe they were removed.

**Comment by Tompage1994** [comment]
> flake8 is failing, not sure if it is connected to these changes though... wouldn't see why. also the extra spaces I thought was causing some errors which is why I believe they were removed.

Indeed it was unrelated, looks as though flake8 updated and has subsequently failed. I've raised #283 to fix the issue so that should be merged first, then this can be

**Pull request merged**
