### PR TITLE
Remove ansible.galaxy library dependency

### LINKED ISSUE #59: Galaxy import is broken for build in 2.12 ansible
ah_repository is broken in 2.12+ 
I did a test and used 2.11.8 and it worked, but newer versions it is broken
Here is the result when you run on newer
```
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File \"/home/excalibrax/.ansible/tmp/ansible-tmp-1644767065.8088183-714711-104834170088452/AnsiballZ_ah_repository.py\", line 107, in <module>
    _ansiballz_main()
  File \"/home/excalibrax/.ansible/tmp/ansible-tmp-1644767065.8088183-714711-104834170088452/AnsiballZ_ah_repository.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/excalibrax/.ansible/tmp/ansible-tmp-1644767065.8088183-714711-104834170088452/AnsiballZ_ah_repository.py\", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.redhat_cop.ah_configuration.plugins.modules.ah_repository', init_globals=dict(_module_fqn='ansible_collections.redhat_cop.ah_configuration.plugins.modules.ah_repository', _modlib_path=modlib_path),
  File \"/usr/lib64/python3.10/runpy.py\", line 209, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib64/python3.10/runpy.py\", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File \"/usr/lib64/python3.10/runpy.py\", line 86, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_ah_repository_payload_4y98v39o/ansible_ah_repository_payload.zip/ansible_collections/redhat_cop/ah_configuration/plugins/modules/ah_repository.py\", line 103, in <module>
  File \"/tmp/ansible_ah_repository_payload_4y98v39o/ansible_ah_repository_payload.zip/ansible_collections/redhat_cop/ah_configuration/plugins/module_utils/ah_module.py\", line 12, in <module>
  File \"/home/excalibrax/.local/lib/python3.10/site-packages/ansible/galaxy/__init__.py\", line 28, in <module>
    import ansible.constants as C
  File \"/home/excalibrax/.local/lib/python3.10/site-packages/ansible/constants.py\", line 14, in <module>
    from ansible.config.manager import ConfigManager, ensure_type
  File \"/home/excalibrax/.local/lib/python3.10/site-packages/ansible/config/manager.py\", line 21, in <module>
    from ansible.module_utils.common.yaml import yaml_load
ModuleNotFoundError: No module named 'ansible.module_utils.common.yaml'
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}
```

It looks like a dependency error somewhere, but I haven't succeeded in tracking it down. 
@Tompage1994 If you could have a look.

### PR DESCRIPTION
**Pull request by Tompage1994**
### What does this PR do?
Removes the ansible.galaxy dependency

### How should this be tested?
Probably easiest to run manually. I have been running to verify:

```
ansible -m  redhat_cop.ah_configuration.ah_build -a "path=. force=true output_path=test" localhost -c local
```

### Is there a relevant Issue open for this?
Provide a link to any open issues that describe the problem you are solving.
resolves #59 

### Other Relevant info, PRs, etc.
N/A

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
Doesn't this break build entirely? as in we should remove that module?
otherwise looks good

**Comment by sean-m-sullivan** [comment]
Found the old code
https://github.com/redhat-cop/ah_configuration/blob/2be9f5fba16699f4736c30339770a67ae59cd5c6/roles/publish/tasks/main.yml#L13

**Comment by Tompage1994** [comment]
I don't think this breaks build? It's working for me with this change. It's invoking ansible-galaxy collection build under the cover

**Comment by sean-m-sullivan** [comment]
I did not read the change enough, with the run command >< :P, tested

**Review by sean-m-sullivan — APPROVED** [review]
LGTM

**Pull request merged**
