### PR TITLE
README docfix

### PR DESCRIPTION
**Pull request by syntaxsdev**
fixed table readme for ee-image

# What does this PR do?

Fixed the table for the README.md for the role `ee-image`

# How should this be tested?
No test needed

# Is there a relevant Issue open for this?

There is no relevant issue or PR for this

# Other Relevant info, PRs, etc

N/A

### CODE REVIEW

**Comment by syntaxsdev** [comment]
PR just had Readme fixes, ready to merge

**Comment by sean-m-sullivan** [comment]
Doing a review on this, the new name was likely put in docs to be hopeful, and I believe we aren't able to rename image names through the API, the module [does not support it, ref here](https://github.com/ansible/galaxy_collection/blob/805fd7d27f5728992f51b1623859918daeff658d/plugins/modules/ah_ee_image.py#L26)

Additionally, the present we have set to be quoted so it shows up as a variable, as referenced below
[here](https://github.com/ansible/galaxy_collection/tree/devel/roles/collection_repository#collection-repository-variables)
[here](https://github.com/redhat-cop/controller_configuration/tree/devel/roles/projects#project-variables)

We welcome the contributions, and feedback to improve the docs, I do not doubt we have some inconsistencies and typos around that we've missed, I hope you find more!

**Comment by syntaxsdev** [comment]
> Doing a review on this, the new name was likely put in docs to be hopeful, and I believe we aren't able to rename image names through the API, the module [does not support it, ref here](https://github.com/ansible/galaxy_collection/blob/805fd7d27f5728992f51b1623859918daeff658d/plugins/modules/ah_ee_image.py#L26)
> 
> Additionally, the present we have set to be quoted so it shows up as a variable, as referenced below [here](https://github.com/ansible/galaxy_collection/tree/devel/roles/collection_repository#collection-repository-variables) [here](https://github.com/redhat-cop/controller_configuration/tree/devel/roles/projects#project-variables)
> 
> We welcome the contributions, and feedback to improve the docs, I do not doubt we have some inconsistencies and typos around that we've missed, I hope you find more!

Thanks, I have corrected the suggestions.

**Review by sean-m-sullivan — APPROVED** [review]
Looks good, thanks for the fix!

**Pull request merged**
