### PR TITLE
Run auto_approve workflow in CI for all versions

### PR DESCRIPTION
**Pull request by Tompage1994**
# What does this PR do?

Run auto_approve workflow in CI for all versions

### CODE REVIEW

**Comment by Tompage1994** [comment]
If tests pass then please approve @sean-m-sullivan

**Review by djdanielsson — APPROVED** [review]
LGTM

**Comment by sean-m-sullivan** [comment]
Does not look good, will need to look into reasons why its failing

**Comment by djdanielsson** [comment]
Why are there two 4.5 tests?

**Comment by sean-m-sullivan** [comment]
There are two of every test because of push and merge being two seperate events happening same time here. However I was running tests on this and this fix that works for master and 4.6, does not work for previous versions. I'm investigating and trying to figure out What gasket blew. for now closing this.

**Pull request closed without merging**
