### PR TITLE
collection_remote: set sync_dependencies default to PAH default

### PR DESCRIPTION
**Pull request by dbk-rabel**
# What does this PR do?

The default of sync_dependencies in PAH is True. So the ah_configuration collection should also use True as the default value.

### CODE REVIEW

**Review by djdanielsson — CHANGES_REQUESTED** [review]
I'm confused, in your PR comment you said change to False but the change is to True

**Comment by dbk-rabel** [comment]
> I'm confused, in your PR comment you said change to False but the change is to True

Oh yeah. Thanks for the hint. I fixed it now.

**Comment by dbk-rabel** [comment]
To clarify: The change is to True. The commit was correct. I edited the PR comment.

**Review by djdanielsson — APPROVED** [review]
LGTM

**Comment by djdanielsson** [comment]
I am going to merge this because the CI failing isn't related to this change from what I can tell

**Pull request merged**
